---
- name: "Worker node: Creating Occopus data directory"
  file:
    path: /var/lib/micado/occopus/data/
    state: directory
    mode: 0775
    recurse: yes

- name: "Worker node: Deploying credential file for Occopus"
  copy:
      src: "{{ cred_path }}"
      dest: "/var/lib/micado/occopus/data/auth_data.yaml"

- name: "Worker node: Deploying cloud-config for workers"
  template:
    src: worker_node/cloud_init_worker.yaml.j2
    dest: /var/lib/micado/toscasubmitter/system/cloud_init_worker.yaml
    mode: 0644

- name: "Worker node: Deploying Occopus infrastructure descriptor"
  template:
    src: worker_node/temp_infrastructure_descriptor.yaml.j2
    dest: /var/lib/micado/toscasubmitter/system/infrastructure_descriptor.yaml
    mode: 0644
